[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[identity]
  external_providers = []

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "development" }

[context.branch-deploy]
  environment = { NODE_ENV = "development" }

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "no-cache"